[WIP] Relecture
entwanne/sortie-de-python-3-6 pull request #1
Opened 2016-11-30 11:05 UTC by Vayel

2016-11-30 11:06 UTC, Vayel commented
L'exemple suivant n'est pas très parlant, vu qu'on a du mal à imaginer un range comme une io.

```py
return [i async for i in async_range(0, 10)]
```

2016-11-30 11:30 UTC, Vayel commented
> Nous pouvons alors avoir une seconde coroutine, print_lines, qui itérera sur ce générateur pour afficher les lignes produites.  
> ...  
> Et à l'utilisation :

Peut-être exécuter une autre coroutine de manière concurrente, pour qu'on se rende bien compte de l'aspect asynchrone.

2016-11-30 11:45 UTC, Vayel commented
Je bloque sur le paragraphe concernant la généralisation de l'interpolation de chaînes (PEP 501). Je vais essayer de lire la PEP pour remédier à ça.

2016-11-30 13:06 UTC, entwanne requested changes
Attention aussi, j'ai dû modifier le commit HEAD en raison d'une adresse mail invalide.

2016-11-30 13:06 UTC, entwanne commented on tl-dr-resume-des-principales-nouveautes.md
> +    Ils fonctionneront comme des générateurs habituels, mais seront non bloquants et à utiliser depuis d'autres coroutines.
J'ai du mal avec la formulation. Ce n'est pas le générateur qui est non-bloquant, c'est la boucle événementielle qui l'exécute qui peut se permettre d'exécuter d'autres tâches pendant que, justement, le générateur bloque.

2016-11-30 13:06 UTC, entwanne commented on principales-nouveautes.md
> +Nous avons ici notre propre type d'objet (`UserHome`), qui est interprété par les fonctions système (`os.listdir` dans notre cas) comme un chemin de fichier.
Je serais plutôt d'avis d'ajouter un « s » au « fonctions système » du TL;DR.

2016-11-30 13:06 UTC, entwanne commented on ce-que-lon-peut-attendre-pour-la-version-3-7.md
> + -  `?.[]` (*None-aware indexing*) permet de faire de même lors de l'accès aux éléments d'un conteneur (`container[...]`).
Mais maintenant ça répète 3 fois le mot « permet », ce qui fait un peu lourd.

2016-11-30 13:09 UTC, entwanne commented
Pour l'exemple sur la liste en intension asynchrone, je voulais un exemple le plus simple possible.

Et quelle autre coroutine voudrais-tu exécuter en concurrence ?

2016-11-30 14:17 UTC, Vayel commented
> Pour l'exemple sur la liste en intension asynchrone, je voulais un exemple le plus simple possible.

Je n'avais pas vu que `async_range` était défini juste au-dessus. Je pense que ça convient du coup.

> Et quelle autre coroutine voudrais-tu exécuter en concurrence ?

Un compteur tout bête. Ou alors lire deux fichiers en même temps.

2016-11-30 14:25 UTC, entwanne commented
Ok, je vais partir sur les deux fichiers.

2016-11-30 16:58 UTC, entwanne commented on principales-nouveautes.md
> +| {'z': 0, 'x': 5, 'y': 1}
Je ne suis pas convaincu par cette modification

2016-11-30 16:58 UTC, entwanne commented on principales-nouveautes.md
> +| Les paragraphes qui suivent demandent des connaissance sur le concept de générateur en Python et de programmation asynchrone.
J'ai adapté le changement dans le commit #32a6b7

2016-11-30 21:18 UTC, Vayel commented on principales-nouveautes.md
> +| {'z': 0, 'x': 5, 'y': 1}
C'est pour bien montrer qu'on conserve le même ordre, que le dictionnaire n'est trié ni par les valeurs ni par les clés.

2016-11-30 23:13 UTC, entwanne commented on principales-nouveautes.md
> +| {'z': 0, 'x': 5, 'y': 1}
Les exemples précédents tendent déjà à le montrer.
Il s'agit ici juste d'indiquer que l'ordre est bien conservé, contrairement à un CPython ≤ 3.5.

2016-12-02 17:37 UTC, entwanne commented
J'ai intégré les modifications validées à la branche `master`.

2016-12-02 17:37 UTC, closed without merging

2016-12-02 17:40 UTC, Vayel commented
@entwanne je travaille actuellement sur la reformulation de la partie sur le préfixe `i`. Après lecture de la PEP, je pense que je n'avais pas compris ce passage parce que les limites de `f` n'étaient pas claires.

2016-12-03 01:48 UTC, entwanne commented
Il faut garder à l'esprit que le contenu est envoyé en validation, et que Python 3.6 est prévue pour le 16 décembre. Qu'il y a-t-il d'important à reformuler ?

2016-12-03 09:07 UTC, Vayel commented
Pour moi, il faudrait inverser l'ordre des paragraphes. D'abord dire qu'avec `f` on ne peut pas réutiliser le "template" ni personnaliser le formatage, puis introduire `i`, pour pallier ça.

Sans lire la PEP, je ne comprenais absolument pas la phrase "cette PEP demande l'ajout d'un préfixe i tel que f'Bonjour {name}' soit équivalent à format(i'Bonjour {name}').". Mais je ne suis pas une référence non plus.